/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "calcTest7n.check" instead.
 */

#include <check.h>

#include "logic_model.h"

#define EPSFOUR 0.0001
#define MAX_STRING_SIZE 16384


// TEST7

START_TEST(calc7)
{

char expression[MAX_STRING_SIZE] = "((2^((((((((2^(1^-1+1)+1)^(-1))+1^-2^-2^1^1)^(2/3)*1^(2^2^(1)^(2)*(1)))*1+1)^2)*1)+3)^2))"; 
char outputStr[MAX_STRING_SIZE] = {0};
TestCalculate(expression, outputStr, 0);

ck_assert_str_eq("-3", outputStr);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("SmartCalc");
    TCase *tc1_1 = tcase_create("SmartCalc");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc7);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
