/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "calcTest.check" instead.
 */

#include <check.h>

#include "logic_model.h"

#define EPS 0.0000009
#define EPSFOUR 0.0001
#define MAX_STRING_SIZE 16384


// TEST1

START_TEST(calc1)
{

char expression[MAX_STRING_SIZE] = "5+5"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("10",NULL), strtold(outputStr,NULL), EPS);

// TEST3

}
END_TEST

START_TEST(calc3)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+-5678.1234*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)+6)"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("-40920.7057214",NULL), strtold(outputStr,NULL), EPS);

// TEST4

}
END_TEST

START_TEST(calc4)
{

char expression[MAX_STRING_SIZE] = "1000000^99"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("inf", outputStr);

// TEST5

}
END_TEST

START_TEST(calc5)
{

char expression[MAX_STRING_SIZE] = "3.09mod"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("NAN encountered during calculation", outputStr);

// TEST6

}
END_TEST

START_TEST(calc6)
{

char expression[MAX_STRING_SIZE] = "5*6/7"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("4.2857142857", outputStr);

// TEST7

}
END_TEST

START_TEST(calc7)
{

char expression[MAX_STRING_SIZE] = "5/6*7"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("5.8333333331", outputStr);

// TEST8

}
END_TEST

START_TEST(calc8)
{

char expression[MAX_STRING_SIZE] = "5-6+7"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("6.0", outputStr);

// TEST9

}
END_TEST

START_TEST(calc9)
{

char expression[MAX_STRING_SIZE] = "5+6-7"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("4.0", outputStr);

// TEST10

}
END_TEST

START_TEST(calc10)
{

char expression[MAX_STRING_SIZE] = "-(-5+aboba)"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered", outputStr);

// TEST11

}
END_TEST

START_TEST(calc11)
{

char expression[MAX_STRING_SIZE] = "-5--6++7"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("8.0", outputStr);

// TEST12

}
END_TEST

START_TEST(calc12)
{

char expression[MAX_STRING_SIZE] = "soc(0.99)"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered", outputStr);


// TEST13

}
END_TEST

START_TEST(calc13)
{

char expression[MAX_STRING_SIZE] = "5+-6-+7"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_str_eq("-8.0", outputStr);

// ------
// WITH X
// ------

}
END_TEST

// TESTX1

START_TEST(calcx1)
{

char expression[MAX_STRING_SIZE] = "5+x";
char x[MAX_STRING_SIZE] = "5+5"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("15",NULL), strtold(outputStr,NULL), EPS);

// TESTX4

}
END_TEST

START_TEST(calcx4)
{

char expression[MAX_STRING_SIZE] = "45/x";
char x[MAX_STRING_SIZE] = "9";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("5",NULL), strtold(outputStr,NULL), EPS);

// TESTX8

}
END_TEST

START_TEST(calcx8)
{

char expression[MAX_STRING_SIZE] = "x*x";
char x[MAX_STRING_SIZE] = "1000000000000000000000000000000000000000000000";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("inf", outputStr);

// TESTX9

}
END_TEST

START_TEST(calcx9)
{

char expression[MAX_STRING_SIZE] = "x^3 + x/2 + 56mod4";
char x[MAX_STRING_SIZE] = "9.4342345235235";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("844.409",NULL), strtold(outputStr,NULL), EPSFOUR);

// TESTX10

}
END_TEST

START_TEST(calcx10)
{

char expression[MAX_STRING_SIZE] = "x^3 + x/2 + 56%4";
char x[MAX_STRING_SIZE] = "9.4342345235235";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("844.409",NULL), strtold(outputStr,NULL), EPSFOUR);

// TESTX11

}
END_TEST

START_TEST(calcx11)
{

char expression[MAX_STRING_SIZE] = "x^2+x^3*(-4 * x)-100";
char x[MAX_STRING_SIZE] = "-1000000";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("-3999999999999000000069632.0", outputStr);

// TESTX11_2

}
END_TEST

START_TEST(calcx11_2)
{

char expression[MAX_STRING_SIZE] = "(x^2+x^3*(-4 * x)-100)-(x^2+x^3*(-4 * x)-100)";
char x[MAX_STRING_SIZE] = "-1000000";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("0",NULL), strtold(outputStr,NULL), EPS);

// TESTX12

}
END_TEST

START_TEST(calcx12)
{

char expression[MAX_STRING_SIZE] = "x^1.1";
char x[MAX_STRING_SIZE] = "-1000000";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);
// printf("\n>>%s<<\n",outputStr);

ck_assert_str_eq("NAN encountered during calculation", outputStr);

// TESTX13

}
END_TEST

START_TEST(calcx13)
{

char expression[MAX_STRING_SIZE] = "x^2-sqrt(x^x)";
char x[MAX_STRING_SIZE] = "64";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

// ck_assert_ldouble_eq_tol(strtold("-6277101735386680763835789423207666416102355444464034512896.0",NULL), strtold(outputStr,NULL), EPS);
ck_assert_str_eq("-inf", outputStr);


// TESTX14

}
END_TEST

START_TEST(calcx14)
{

char expression[MAX_STRING_SIZE] = "cos(acos(tan(atan(sin(x)))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("0.4794255386", outputStr);

// TESTX15

}
END_TEST

START_TEST(calcx15)
{

char expression[MAX_STRING_SIZE] = "cos(acos(tan(atan(sin(sqrt(x))))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("0.6496369391", outputStr);

// TESTX16

}
END_TEST

START_TEST(calcx16)
{

char expression[MAX_STRING_SIZE] = "cos(acos(tan(atan(sin(sqrt(x^sqrt(sqrt((5)*(+5%-4))))))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Brackets are invalid", outputStr);

// TESTX19

}
END_TEST

START_TEST(calcx19)
{

char expression[MAX_STRING_SIZE] = "cos(acos(tan(atan(sin(sqrt(0.35469507876))))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("0.5609747685", outputStr);

// TESTX20

}
END_TEST

START_TEST(calcx20)
{

char expression[MAX_STRING_SIZE] = "=cos(acos(tan(atan(sin(sqrt(0.35469507876))))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered", outputStr);

// TESTX21

}
END_TEST

START_TEST(calcx21)
{

char expression[MAX_STRING_SIZE] = "5";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("5",NULL), strtold(outputStr,NULL), EPS);

// TESTX22

}
END_TEST

START_TEST(calcx22)
{

char expression[MAX_STRING_SIZE] = "5";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("5",NULL), strtold(outputStr,NULL), EPS);

// TESTX23

}
END_TEST

START_TEST(calcx23)
{

char expression[MAX_STRING_SIZE] = "asin(cos(x))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("1.0708",NULL), strtold(outputStr,NULL), EPSFOUR);

// TESTX24

}
END_TEST

START_TEST(calcx24)
{

char expression[MAX_STRING_SIZE] = "asin(cos(sqrt(-x)))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("NAN encountered during calculation", outputStr);

// TESTX25

}
END_TEST

START_TEST(calcx25)
{

char expression[MAX_STRING_SIZE] = "log(x)";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("-0.2291479884", outputStr);

// TESTX26

}
END_TEST

START_TEST(calcx26)
{

char expression[MAX_STRING_SIZE] = "ln(x)";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("-0.5276327421", outputStr);

// TESTX27

}
END_TEST

START_TEST(calcx27)
{

char expression[MAX_STRING_SIZE] = "=fsdfsdfsdf";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered", outputStr);

// TESTX28

}
END_TEST

START_TEST(calcx28)
{

char expression[MAX_STRING_SIZE] = "5(6)(7)";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("210.0", outputStr);

// TESTX30

}
END_TEST

START_TEST(calcx30)
{

char expression[MAX_STRING_SIZE] = "-5-+5--2*+5/+1";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("0.0", outputStr);

// TESTX31

}
END_TEST

START_TEST(calcx31)
{

char expression[MAX_STRING_SIZE] = "-5^-5";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("-0.00032", outputStr);

// TESTX32

}
END_TEST

START_TEST(calcx32)
{

char expression[MAX_STRING_SIZE] = "+5^+5";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("3125.0", outputStr);

// TESTX33

}
END_TEST

START_TEST(calcx33)
{

char expression[MAX_STRING_SIZE] = "+5%+4";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("1.0", outputStr);

// TESTX34

}
END_TEST

START_TEST(calcx34)
{

char expression[MAX_STRING_SIZE] = "-5%-4";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("-1.0", outputStr);

// TESTX35

}
END_TEST

START_TEST(calcx35)
{

char expression[MAX_STRING_SIZE] = "-(-5)%-4";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("1.0", outputStr); // maybe incorrect

// TESTX36

}
END_TEST

START_TEST(calcx36)
{

char expression[MAX_STRING_SIZE] = "--5%-4";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("1.0", outputStr); // maybe incorrect

// TESTX_E_29

}
END_TEST

START_TEST(calcx_E_29)
{

char expression[MAX_STRING_SIZE] = "(+5)-(+5)-(-2)*(+5)/(+1)";
char x[MAX_STRING_SIZE] = "0.59";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("10.0", outputStr);

// TESTX_E_7

}
END_TEST

START_TEST(calcx_E_7)
{

char expression[MAX_STRING_SIZE] = "-0.68*x*x*x*x-0.1*x*x*x-0.01*x*x-0.0*x*x*x";
char x[MAX_STRING_SIZE] = "1000000000000000000000000000000000000000000000";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("-inf", outputStr);

// TESTX_E_6

}
END_TEST

START_TEST(calcx_E_6)
{

char expression[MAX_STRING_SIZE] = "-0.68*x*x*x*x-0.1*x*x*x-0.01*x*x-0.0*x*x*x";
char x[MAX_STRING_SIZE] = "0";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("0",NULL), strtold(outputStr,NULL), EPS);

// TESTX_E_2

}
END_TEST

START_TEST(calcx_E_2)
{

char expression[MAX_STRING_SIZE] = "-(+5-(+6-(-7-(-1-(+3+4+x*-6+-3/-4++5++7)))))";
char x[MAX_STRING_SIZE] = "-54343.43434"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("-326073.35604",NULL), strtold(outputStr,NULL), EPS);

// TESTX_E_3

}
END_TEST

START_TEST(calcx_E_3)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)+6)";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("-40920.7057214",NULL), strtold(outputStr,NULL), EPS);

// TESTX_VAL_1

}
END_TEST

START_TEST(calcx_VAL_1)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)+**6)";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TESTX_VAL_2

}
END_TEST

START_TEST(calcx_VAL_2)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)+&6)";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TESTX_VAL_3

}
END_TEST

START_TEST(calcx_VAL_3)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)+++6)";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TESTX_VAL_4

}
END_TEST

START_TEST(calcx_VAL_4)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)---6)";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);


// TESTX_VAL_5

}
END_TEST

START_TEST(calcx_VAL_5)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)-sqtr(6))";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TESTX_VAL_6

}
END_TEST

START_TEST(calcx_VAL_6)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)-soc(6))";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TESTX_VAL_7

}
END_TEST

START_TEST(calcx_VAL_7)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)-sc(6))";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TESTX_E_18

}
END_TEST

START_TEST(calcx_E_18)
{

char expression[MAX_STRING_SIZE] = "sin(sqrt(x^((-21)^(1/4))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("NAN encountered during calculation", outputStr);

// TESTX_E_69

}
END_TEST

START_TEST(calcx_E_69)
{

char expression[MAX_STRING_SIZE] = "45/x";
char x[MAX_STRING_SIZE] = "0";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Division by zero is impossible", outputStr);

// TESTX_E_69_2

}
END_TEST

START_TEST(calcx_E_69_2)
{

char expression[MAX_STRING_SIZE] = "45.0.0/x";
char x[MAX_STRING_SIZE] = "0";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered", outputStr);


// TESTX_VAL_8

}
END_TEST

START_TEST(calcx_VAL_8)
{

char expression[MAX_STRING_SIZE] = "-(-(-3*(-(-(3*4+x*-6+-3/-4+5+7)*(2/5)+4/(9-5*(5/6))))-5)-s(6))";
char x[MAX_STRING_SIZE] = "-5678.1234";
char outputStr[MAX_STRING_SIZE] = {0}; 
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("Invalid symbols encountered",outputStr);

// TEST2

}
END_TEST

START_TEST(calc2)
{

char expression[MAX_STRING_SIZE] = "-(+5-(+6-(-7-(-1-(+3+4+-54343.43434*-6+-3/-4++5++7)))))"; 
char outputStr[MAX_STRING_SIZE] = {0}; 
TestCalculate(expression, outputStr);

ck_assert_ldouble_eq_tol(strtold("-326073.35604",NULL), strtold(outputStr,NULL), EPS);

// TESTX17

}
END_TEST

START_TEST(calcx17)
{

char expression[MAX_STRING_SIZE] = "cos(acos(tan(atan(sin(sqrt(x^sqrt(sqrt((5)*(+5%4)))))))))";
char x[MAX_STRING_SIZE] = "0.5";
char outputStr[MAX_STRING_SIZE] = {0};
ReplaceX(expression, x);
TestCalculate(expression, outputStr);

ck_assert_str_eq("0.5609747685", outputStr);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("SmartCalc");
    TCase *tc1_1 = tcase_create("SmartCalc");
    Suite *s2 = suite_create("SmartCalcX");
    TCase *tc2_1 = tcase_create("SmartCalcX");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc1);
    tcase_add_test(tc1_1, calc3);
    tcase_add_test(tc1_1, calc4);
    tcase_add_test(tc1_1, calc5);
    tcase_add_test(tc1_1, calc6);
    tcase_add_test(tc1_1, calc7);
    tcase_add_test(tc1_1, calc8);
    tcase_add_test(tc1_1, calc9);
    tcase_add_test(tc1_1, calc10);
    tcase_add_test(tc1_1, calc11);
    tcase_add_test(tc1_1, calc12);
    tcase_add_test(tc1_1, calc13);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, calcx1);
    tcase_add_test(tc2_1, calcx4);
    tcase_add_test(tc2_1, calcx8);
    tcase_add_test(tc2_1, calcx9);
    tcase_add_test(tc2_1, calcx10);
    tcase_add_test(tc2_1, calcx11);
    tcase_add_test(tc2_1, calcx11_2);
    tcase_add_test(tc2_1, calcx12);
    tcase_add_test(tc2_1, calcx13);
    tcase_add_test(tc2_1, calcx14);
    tcase_add_test(tc2_1, calcx15);
    tcase_add_test(tc2_1, calcx16);
    tcase_add_test(tc2_1, calcx19);
    tcase_add_test(tc2_1, calcx20);
    tcase_add_test(tc2_1, calcx21);
    tcase_add_test(tc2_1, calcx22);
    tcase_add_test(tc2_1, calcx23);
    tcase_add_test(tc2_1, calcx24);
    tcase_add_test(tc2_1, calcx25);
    tcase_add_test(tc2_1, calcx26);
    tcase_add_test(tc2_1, calcx27);
    tcase_add_test(tc2_1, calcx28);
    tcase_add_test(tc2_1, calcx30);
    tcase_add_test(tc2_1, calcx31);
    tcase_add_test(tc2_1, calcx32);
    tcase_add_test(tc2_1, calcx33);
    tcase_add_test(tc2_1, calcx34);
    tcase_add_test(tc2_1, calcx35);
    tcase_add_test(tc2_1, calcx36);
    tcase_add_test(tc2_1, calcx_E_29);
    tcase_add_test(tc2_1, calcx_E_7);
    tcase_add_test(tc2_1, calcx_E_6);
    tcase_add_test(tc2_1, calcx_E_2);
    tcase_add_test(tc2_1, calcx_E_3);
    tcase_add_test(tc2_1, calcx_VAL_1);
    tcase_add_test(tc2_1, calcx_VAL_2);
    tcase_add_test(tc2_1, calcx_VAL_3);
    tcase_add_test(tc2_1, calcx_VAL_4);
    tcase_add_test(tc2_1, calcx_VAL_5);
    tcase_add_test(tc2_1, calcx_VAL_6);
    tcase_add_test(tc2_1, calcx_VAL_7);
    tcase_add_test(tc2_1, calcx_E_18);
    tcase_add_test(tc2_1, calcx_E_69);
    tcase_add_test(tc2_1, calcx_E_69_2);
    tcase_add_test(tc2_1, calcx_VAL_8);
    tcase_add_test(tc2_1, calc2);
    tcase_add_test(tc2_1, calcx17);

    srunner_add_suite(sr, s2);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
